# ----------------- 项目全局配置文件 -----------------
# 在这里管理所有的路径、超参数和模型设置

# 1. 路径配置 (Paths)
# 建议所有路径都使用相对路径，以项目根目录为基准
paths:
  # 训练集图像路径
  train_images: "data/train/images/"
  # 验证集图像路径
  val_images: "data/val/images/"
  # 模型权重输出目录
  output_dir: "weights/"
  # 预测结果保存目录
  predict_output: "outputs/prediction_results/"
  # 待预测图像或其所在目录
  predict_input: "data/test_images/"
  # 日志文件目录
  log_dir: "logs/"

# 2. 数据处理配置 (Data Processing)
data:
  # 训练和预测时图像要调整到的尺寸
  img_size: 256
  # 图像通道数
  num_channels: 3
  # 类别数量 (对于二元分割，通常是 1)
  num_classes: 1
  # 数据标准化均值 (使用ImageNet的预训练权重时常用)
  mean: [0.485, 0.456, 0.406]
  # 数据标准化标准差
  std: [0.229, 0.224, 0.225]

# 3. 模型配置 (Model)
model:
  # 分割模型架构，例如 Unet, UnetPlusPlus, DeepLabV3+
  architecture: "Unet"
  # 骨干网络 (encoder)
  encoder: "resnet34"
  # 预训练权重来源
  encoder_weights: "imagenet"
  # 激活函数 (对于BCEWithLogitsLoss, 设为None。若要直接输出概率图，可设为'sigmoid')
  activation: null

# 4. 训练配置 (Train)
train:
  # 训练设备: "cuda" 或 "cpu"
  device: "cuda"
  # 学习率
  learning_rate: 0.0001
  # 批次大小
  batch_size: 4
  # 训练轮次
  epochs: 25
  # 用于保存最佳模型的权重文件名
  best_model_name: "unet_resnet34_best.pth"

# 5. 预测配置 (Predict)
predict:
  # 预测时使用的设备
  device: "cuda"
  # 用于预测的模型权重文件路径 (相对于 output_dir)
  model_name: "unet_resnet34_best.pth"
  # 预测时的批次大小
  batch_size: 8
  # 滑窗预测时的重叠区域大小 (像素)
  overlap: 64