# ----------------- 项目全局配置文件 -----------------
# 管理所有的路径、超参数、模型参数

# 1. 路径配置 (Paths) 使用相对路径，以项目根目录为基准
paths:
  train_dir: "data/train/"  # 训练集图像路径
  val_dir: "data/val/"   # 验证集图像路径
  output_dir: "weights/"  # 模型权重输出目录
  predict_output: "outputs/prediction_results/"  # 预测结果保存目录
  predict_input: "data/test/images/"   # 待预测图像或其所在目录
  log_dir: "logs/"  # 日志文件目录

# 2. 参数配置
vars:
  device: "cuda" # 'cpu' or 'cuda' - edit according to your device

  architecture: "Unet" # 分割模型架构，例如 Unet, UnetPlusPlus, DeepLabV3+
  encoder: "resnet34"  # 骨干网络 (encoder)
  encoder_weights: "imagenet"  # 预训练权重来源
  activation: null # 激活函数 (对于BCEWithLogitsLoss, 设为None。若要直接输出概率图，可设为'sigmoid')
  learning_rate: 0.0001  # 学习率
  batch_size: 4  # 批次大小
  epochs: 100  # 训练轮次
  
  overlap: 64  # 滑窗预测时的重叠区域大小 (像素)
  img_num: 2  # 训练和预测时一次喂给模型的图片张数
  img_size: 256  # 训练和预测时图像要调整到的尺寸
  num_channels: 3  # 图像通道数
  num_classes: 1  # 类别数量 (对于二元分割，通常是 1)
  mean: [0.485, 0.456, 0.406]  # 数据标准化均值 (使用ImageNet的预训练权重时常用)
  std: [0.229, 0.224, 0.225]   # 数据标准化标准差

  predict_model: "weights/best_model_Unet_resnet34_20250710_162544.pth"   # 用于预测的模型权重文件
  predict_image: "data/test/images/L19-11.tif" # 用于预测的影像文件
  predict_patch_size: 512 # 每次处理的小块尺寸 (像素)，可根据显存大小调整
  predict_overlap_rate: 0.25 # 滑窗重叠率，建议0.25 (即25%的重叠)
  predict_strip_height: 512