# -------------------------------------------------------------------
# Conda环境定义文件：负责Python解释器、CUDA和PyTorch等底层依赖
# -------------------------------------------------------------------
name: satellite-seg-env-py39

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.9
  - pip
  - pytorch=2.5.1  
  - torchvision=0.20.1
  - pytorch-cuda=12.1